
import os
DEBUG=True

SQL_TRACK_MODIFICATIONS=False
PROPAGATE_EXCEPTIONS=True
JWT_SECRET_KEY=os.environ["SECRET_KEY"]

JWT_BLACKLIST_ENABLED=True
UPLOADED_IMAGES_DEST=os.path.join("static", "images")